services:
  - type: web
    name: streamlit-04
    env: python
    runtime: python-3.11
    buildCommand: |
      # Backend dependencies
      cd backend
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      
      # Frontend build
      cd ../frontend/news-app
      npm install
      npm run build
      
    startCommand: |
      cd backend
      gunicorn wsgi:application --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker
      
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: SQLITE_PATH
        value: /opt/render/project/src/backend/news.db
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: news-postgres
    databaseName: newsdb
    user: newsuser